'use client';

import {
  addOne,
  initCounterState,
  substractOne,
} from '@/store/counter/counterSlice';
// import { useState } from 'react';
import { useAppSelector, useAppDispatch } from '../../store/index';
import { useEffect } from 'react';

interface Props {
  value?: number;
}

// Generated by https://quicktype.io

export interface CounterResponse {
  count: number;
}

const getApiCounter = async (): Promise<CounterResponse> => {
  const data = await fetch('/api/counter').then((res) => res.json());
  return data;
};

export const CardCounter = ({ value = 0 }: Props) => {
  const count = useAppSelector((state) => state.counter.count);
  const dispatch = useAppDispatch();
  // const [count, setCount] = useState(value);

  // useEffect(() => {
  //   dispatch(initCounterState(value));
  // }, [dispatch, value]);

  useEffect(() => {
    getApiCounter().then(({ count }) => {
      dispatch(initCounterState(count));
    });
  }, [dispatch]);

  function increment() {
    // setCount(count + 1);
    dispatch(addOne());
  }

  function decrement() {
    // setCount(count - 1);
    dispatch(substractOne());
  }

  return (
    <>
      <span className='text-9xl'>{count}</span>
      <div className='flex'>
        <button
          onClick={decrement}
          className='flex items-center justify-center p-2 rounded-xl bg-gray-900 text-white hover:bg-gray-600 transition-all w-[100px] mr-2'
        >
          -1
        </button>
        <button
          onClick={increment}
          className='flex items-center justify-center p-2 rounded-xl bg-gray-900 text-white hover:bg-gray-600 transition-all w-[100px] mr-2'
        >
          +1
        </button>
      </div>
    </>
  );
};
